version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.7.4
    ports:
      - "5672:5672"
      - "15672:15672"
  backend1:
    container_name: server
    build:
      context: ./backend1
      dockerfile: ./Dockerfile
    ports:
      - "5001:5001"
  backend2:
    container_name: notification_api
    env_file:
        "./backend2/.env.local"
    build:
      context: ./backend2
      dockerfile: ./Dockerfile
    depends_on: 
      - "rabbitmq"
    ports:
      - "5002:5002"
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    links:
      - "backend1"